name: uni_links_web
description: A web implementation of the Uni Links platform interface.
version: 0.1.0
publish_to: "none" # Remove this line if you wish to publish to pub.dev
homepage: https://github.com/avioli/uni_links/tree/master/uni_links_web

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  uni_links_platform_interface:
    path: ../uni_links_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.17.5 <3.0.0"

flutter:
  plugin:
    platforms:
      web:
        pluginClass: UniLinksPlugin
        fileName: "uni_links_web.dart"
